Fix acquire IP from Rancher
The IP won't be set immediately so we need to wait for it.

Also fix finding nameserver, in which case Rancher would modify and comment out
old nameservers.

diff --git a/image/base/startvm b/image/base/startvm
--- a/image/base/startvm
+++ b/image/base/startvm
@@ -79,12 +79,35 @@ cidr2mask() {
   echo $mask
 }
 
+RETRY_TIMES=10
+RETRY_INTERVAL=5
+if [[ $IP_PREFIX ]]
+then
+	ready=0
+	for i in `seq 1 $RETRY_TIMES`
+	do
+		tmp=`ip addr show dev $IFACE | grep "inet $IP_PREFIX"`
+		if [ $? -eq 0 ]
+		then
+			ready=1
+			break
+		fi
+		echo Waiting to get ip with prefix $IP_PREFIX
+		sleep $RETRY_INTERVAL
+	done
+	if [ $ready -eq 0 ]
+	then
+		echo "Fail to get the ip address prefix with $IP_PREFIX"
+		exit 1
+	fi
+fi
+
 MAC=`ip addr show $IFACE | grep ether | sed -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*\$//g' | cut -f2 -d ' '`
 IP=`ip addr show dev $IFACE | grep "inet $IP_PREFIX" | awk '{print $2}' | cut -f1 -d/`
 CIDR=`ip addr show dev $IFACE | grep "inet $IP_PREFIX" | awk '{print $2}' | cut -f2 -d/`
 NETMASK=`cidr2mask $CIDR`
 GATEWAY=`ip route get 8.8.8.8 | grep via | cut -f3 -d ' '`
-NAMESERVER=( `grep nameserver /etc/resolv.conf | cut -f2 -d ' '` )
+NAMESERVER=( `grep nameserver /etc/resolv.conf | grep -v "#" | cut -f2 -d ' '` )
 NAMESERVERS=`echo ${NAMESERVER[*]} | sed "s/ /,/"`
 
 cat > /etc/dnsmasq.conf << EOF
